-- Run only in DB2. Never run this migration in the main authentication database (DB1).
create table if not exists public.ai_student_profiles (
  student_id text primary key,
  dynamic_summary jsonb not null default '{}'::jsonb,
  current_step integer not null default 1 check (current_step between 1 and 5),
  milestone_flags jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
create table if not exists public.chat_history (
  id bigint generated by default as identity primary key,
  student_id text not null references public.ai_student_profiles(student_id) on delete cascade,
  role text not null check (role in ('student','teacher','system')),
  content text not null,
  created_at timestamptz not null default now()
);
create table if not exists public.curriculum_paths (
  id bigint generated by default as identity primary key,
  path_key text unique not null,
  title text not null,
  required_step integer not null default 5,
  payload jsonb not null default '{}'::jsonb,
  active boolean not null default true
);
alter table public.ai_student_profiles enable row level security;
alter table public.chat_history enable row level security;
alter table public.curriculum_paths enable row level security;
-- No anon/authenticated policies: DB2 is reachable only through the Worker with its service role secret.
create index if not exists chat_history_student_created_idx on public.chat_history(student_id,created_at desc);
